shared:
    image: node:14
    annotations:
        publish: &publish
            steps:
                - install: npm install screwdriver-template-main
                - publish: ./node_modules/.bin/template-publish
        validate: &validate
            steps:
                - install: npm install screwdriver-template-main
                - validate: ./node_modules/.bin/template-validate
jobs:
    publish-test:
        <<: *publish
        environment:
            SD_TEMPLATE_PATH: ./sd-publish-test-template.yaml
    publish-invalid:
        <<: *publish
        environment:
            SD_TEMPLATE_PATH: ./sd-invalid-template.yaml
    publish-trusted:
        <<: *publish
        environment:
            SD_TEMPLATE_PATH: ./sd-trusted-template.yaml
    publish-distrusted:
        <<: *publish
        environment:
            SD_TEMPLATE_PATH: ./sd-distrusted-template.yaml
    validate-valid:
        <<: *validate
        environment:
            SD_TEMPLATE_PATH: ./sd-init-template.yaml
    validate-invalid:
        <<: *validate
        environment:
            SD_TEMPLATE_PATH: ./sd-invalid-template.yaml
    init-test-template:
        <<: *publish
        environment:
            SD_TEMPLATE_PATH: ./sd-init-template.yaml
    init-test-trusted-template:
        <<: *publish
        environment:
            SD_TEMPLATE_PATH: ./sd-trusted-template.yaml
    init-test-distrusted-template:
        <<: *publish
        environment:
            SD_TEMPLATE_PATH: ./sd-distrusted-template.yaml
