shared:
    image: node:14
    annotations:
        publish: &publish
            steps:
                - install: npm install screwdriver-template-main
                - publish: ./node_modules/.bin/template-publish
jobs:
    publish-valid:
        <<: *publish
        environment:
            SD_TEMPLATE_PATH: ./sd-init-template.yaml
    publish-invalid:
        <<: *publish
        environment:
            SD_TEMPLATE_PATH: ./sd-invalid-template.yaml
    use-template:
        template: screwdriver-cd-test/test-template@1.0.0
    custom-template:
        image: node:12
        template: screwdriver-cd-test/test-template@1.0.0
        steps:
            - preinstall: echo 'preinstall'
            - postinstall: echo 'postinstall'
            - pretest: echo 'pretest'
            - test: echo 'override'
            - posttest: echo 'posttest'
